sudo: false
language: node_js
node_js:
  - "8"
git:
  depth: 10
before_install:
  - "nvm use $TRAVIS_NODE_VERSION"
  - "npm install -g npm@latest"
script:
  - "npm test"
after_success:
  - |

      $(npm bin)/set-up-ssh --key "$encrypted_b71902191a56_key" \
                            --iv  "$encrypted_b71902191a56_iv" \
                            --path-encrypted-key ".github_deploy_key.enc"

  - |

      if [[ "$(git show --no-patch --format=\"%B\" $TRAVIS_COMMIT)" =~ "[deploy site]" ]]; then
        $(npm bin)/update-branch --commands "rm .gitignore; \
                                             touch .nojekyll; \
                                             mkdir ../site; \
                                             cp -r . ../site; \
                                             mv ../site ./site;" \
                                 --commit-message "Update content [ci skip]" \
                                 --directory "site" \
                                 --distribution-branch "gh-pages" \
                                 --source-branch "master"
      fi

