sudo: false
language: node_js
node_js:
  - "6"
git:
  depth: 10
before_install:
  - "nvm use $TRAVIS_NODE_VERSION"
  - "npm install -g npm@latest"
script:
  - "npm test"
after_success:
  - |

      $(npm bin)/set-up-ssh -k "$encrypted_c522fbe368e1_key" \
                            --iv "$encrypted_c522fbe368e1_iv" \
                            --path-encrypted-key ".github_deploy_key.enc"

  - |

      if [[ "$(git show --no-patch --format=\"%B\" $TRAVIS_COMMIT)" =~ "[deploy site]" ]]; then
        $(npm bin)/update-branch --commands "mkdir ../site; \
                                             cp -r . ../site; \
                                             mv ../site ./site; \
                                             rm ./site/.gitignore" \
                                 --commit-message "Update content [ci skip]" \
                                 --directory "site" \
                                 --distribution-branch "gh-pages" \
                                 --source-branch "master"
      fi
